<div
    class="min-w-screen
        h-screen
        animated
        hidden
        fadeIn
        faster
        fixed
        left-0
        top-0
        flex
        justify-center
        items-center
        inset-0
        z-50
        outline-none 
        focus:outline-none
        bg-no-repeat
        bg-center
        bg-cover"
    id="edit-courrier">
    <div
        onclick="closeModal('edit-courrier')"
        class="absolute
            bg-black
            opacity-80
            inset-0
            z-0">
    </div>
    <div
        class="w-full
            max-w-lg
            p-5
            relative
            mx-auto
            my-auto
            rounded-xl
            shadow-lg
            bg-white">
        <div
            class="w-full
                bg-white
                rounded-lg
                lg:rounded-l-none">
            <h3
                class="text-3xl
                    text-center">Modifer Courrier!</h3>
            <form
                id="edit-courrier-form"
                action="admin/editCourrier"
                method="POST"
                class="px-6
                    pt-6
                    pb-8
                    mb-4
                    bg-white
                    rounded">
				<input
                    id="courrier-id"
                    type="hidden"
                    name="id" />
                <div
                    class="mb-4">
                    <label
                        class="block
                            mb-2
                            text-sm
                            font-bold
                            text-gray-800"
                        for="full_name">
                        Numero Inscription
                    </label>
                    <input 
                        class="border-b-2
                            border-blue-600 
                            outline-none 
                            w-full px-3 py-2 
                            text-sm 
                            leading-tight 
                            text-gray-900 
                            rounded 
                            shadow 
                            appearance-none 
                            focus:outline-none 
                            focus:shadow-outline"
                        type="text"
                        name="numero_inscription"
                        placeholder="Numero Inscription" />
                </div>
                <div
                    class="mb-4">
                    <label
                        class="block
                            mb-2
                            text-sm
                            font-bold
                            text-gray-800"
                        for="designateur">
                        Designateur
                    </label>
                    <input
                        class="border-b-2
                            border-blue-600
                            outline-none
                            w-full
                            px-3
                            py-2
                            text-sm
                            leading-tight
                            text-gray-900
                            rounded
                            shadow
                            appearance-none
                            focus:outline-none
                            focus:shadow-outline"
                        type="text"
                        name="designateur" 
                        placeholder="Designateur" />
                </div>
                <div
                    class="mb-4">
                    <label
                        class="block
                            mb-2
                            text-sm
                            font-bold
                            text-gray-800"
                        for="destination">
                        Destination
                    </label>
                    <input
                        class="border-b-2
                            border-blue-600
                            outline-none
                            w-full
                            px-3
                            py-2
                            mb-3
                            text-sm
                            leading-tight
                            text-gray-900
                            rounded
                            shadow
                            appearance-none
                            focus:outline-none
                            focus:shadow-outline"
                        type="text"
                        name="destination"
                        placeholder="Destination"/>
                </div>
                <div
                    class="mb-4">
                    <label
                        class="block
                            mb-2
                            text-sm
                            font-bold
                            text-gray-800"
                        for="date_depart">
                        Date Depart
                    </label>
                    <input
                        class="border-b-2
                            border-blue-600
                            outline-none
                            w-full
                            px-3
                            py-2
                            text-sm
                            leading-tight
                            text-gray-900
                            rounded
                            shadow
                            appearance-none
                            focus:outline-none
                            focus:shadow-outline"
                        type="date"
                        format="jj/mm/yyyy"
                        name="date_depart"
                        placeholder="Date Depart" />
                </div>
                <div
                    class="mb-4">
                    <label
                        class="block
                            mb-2
                            text-sm
                            font-bold
                            text-gray-800"
                        for="date_arrive">
                        Date Arrive
                    </label>
                    <input
                        class="border-b-2
                            border-blue-600
                            outline-none
                            w-full
                            px-3
                            py-2
                            text-sm
                            leading-tight
                            text-gray-900
                            rounded
                            shadow
                            appearance-none
                            focus:outline-none
                            focus:shadow-outline"
                        type="date"
                        name="date_arrive"
                        placeholder="Date Arrive" />
                </div>
                <div
                    class="mb-6
                        text-center">
                    <button
                        class="w-full
                            flex
                            justify-center
                            px-4
                            py-2
                            font-bold
                            text-white
                            bg-blue-500
                            rounded-full
                            hover:bg-blue-700
                            focus:outline-none
                            focus:shadow-outline"
                        type="submit">
						<svg class="w-6 h-6 mx-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
							<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"></path>
						</svg>
                        Modifer
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>